development:
  dialect: postgres
  database: lion_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: lion_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  dialect: postgres
  database: lion_production
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 25
